services:

  jstanek-website:
    image: haproxy
    container_name: jstanek-website
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8765:80
    networks:
      - jstanek-website

  jstanek-be:
    build:
      context: ./be
      dockerfile: Dockerfile
      network: host
    container_name: jstanek-website-be
    restart: always
    networks:
      - jstanek-website

  jstanek-fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - ENV_FRONTEND_API_PATH=/api
    container_name: jstanek-website-fe
    restart: always
    networks:
      - jstanek-website

networks:
  jstanek-website:
