version: '3.7'
services:

  jstanek-be:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: jstanek-website-be
    networks:
      - jstanek-website

  jstanek-fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://jstanek-be:8000
    ports:
      - "3000:3000"
    container_name: jstanek-website-fe
    networks:
      - jstanek-website

networks:
  jstanek-website:
