version: '3.7'
services:

  jstanek-website:
    image: haproxy
    container_name: jstanek-website
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8765:80
    networks:
      - jstanek-website

  jstanek-be:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: jstanek-website-be
    networks:
      - jstanek-website

  jstanek-fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - ENV_FRONTEND_API_PATH=/api
        - ENV_FRONTEND_WS_PATH=/ws
    container_name: jstanek-website-fe
    networks:
      - jstanek-website

networks:
  jstanek-website:


